name: MorganDMead
favicon: null
layout_spectrum: 0.5422638030722737
typography_spectrum: 0.6185424278955907
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d1ccac'
    - '#898673'
    - '#2c2924'
    - '#54534f'
    - '#abab91'
  brandStrength: 0.5
  lightness: 0.32303726859390736
  saturation: 0.8125
  rhythmicContrast: 0.6952377699781209
purpose: []
