name: MorganDMead
favicon: null
layout_spectrum: 0.5422638030722737
typography_spectrum: 0.6185424278955907
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.554874837398529
  lightness: 0.32303726859390736
  saturation: 0.8556755383033305
  rhythmicContrast: 0.6952377699781209
purpose: []
